from enum import Enum


class InvoiceStatus(str, Enum):
    GUELTIG = "GUELTIG"
    UNGUELTIG = "UNGUELTIG"
    MAHNUNG = "MAHNUNG"
    PRIVAT_RECHNUNG = "PRIVAT_RECHNUNG"
    DUPLIKAT = "DUPLIKAT"


class NotificationType(str, Enum):
    NONE = "NONE"
    ACCOUNTING_INFO = "ACCOUNTING_INFO"
    SUPPLIER_CORRECTION = "SUPPLIER_CORRECTION"
    REDLINGHOFER_CORRECTION = "REDLINGHOFER_CORRECTION"
    DUPLICATE_ALERT = "DUPLICATE_ALERT"


class RoutingFamily(str, Enum):
    COMPANY_PAYABLE = "COMPANY_PAYABLE"
    PRIVATE_PAYABLE = "PRIVATE_PAYABLE"
    PRIVATE_REVIEW_HOLD = "PRIVATE_REVIEW_HOLD"
    AUTO_PAID_CARD = "AUTO_PAID_CARD"
    REMINDER_REVIEW_HOLD = "REMINDER_REVIEW_HOLD"
    INVALID_HOLD = "INVALID_HOLD"
    DUPLICATE_HOLD = "DUPLICATE_HOLD"


class PaymentType(str, Enum):
    UEBERWEISUNG = "UEBERWEISUNG"
    AUTOMATISCH_BEZAHLT = "AUTOMATISCH_BEZAHLT"


class ArtifactType(str, Enum):
    SOURCE_DOCUMENT = "SOURCE_DOCUMENT"
    STAMPED_PDF = "STAMPED_PDF"
    PAYMENT_XML = "PAYMENT_XML"
    NOTIFICATION_DRAFT = "NOTIFICATION_DRAFT"


class AuditEventType(str, Enum):
    INGESTED = "INGESTED"
    EXTRACTED = "EXTRACTED"
    SCREENED = "SCREENED"
    NORMALIZED = "NORMALIZED"
    DUPLICATE_CHECKED = "DUPLICATE_CHECKED"
    VALIDATED = "VALIDATED"
    DECISION_MADE = "DECISION_MADE"
    NOTIFICATION_DRAFTED = "NOTIFICATION_DRAFTED"
    ROUTING_PLANNED = "ROUTING_PLANNED"
    XML_PLANNED = "XML_PLANNED"


class ValidationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class XmlDisposition(str, Enum):
    NOT_ALLOWED = "NOT_ALLOWED"
    PLAN_ONLY = "PLAN_ONLY"
    GENERATE_AND_STORE = "GENERATE_AND_STORE"


class AmountBand(str, Enum):
    MISSING = "MISSING"
    LE_400 = "LE_400"
    LE_10000 = "LE_10000"
    GT_10000 = "GT_10000"
